---
- name: Creating users
  hosts: all
#  vars:
#    - usr: testuser
  var_files:
    - vars.yml
  tasks:
  - name: Creating user {{ usr }}
    win_user:
      name: user_{{ usr }}
      state: present